config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end
  root 'welcome#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to edit_question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to edit_question_path(@question)
  end

  private
    def answer_params
      params.require(:answer).permit(:text)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])

    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    redirect_to questions_path
  end

  private
    def question_params
      params.require(:question).permit(:text)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/_answer.html.erb
<p>
  <%= answer.text %>
</p>

app/views/answers/_form.html.erb
<%= form_with(model: [ @question, @question.answers.build ],
  local: true) do |form| %>
  <p>
    <%= form.text_field :text %><br>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poll</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to 'home', '/' %>
      <%= link_to 'questions', questions_path %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: @question, local: true) do |form| %>

  <% if @question.errors.any? %>
    <ul class="error-list">
      <% @question.errors.full_messages.each do |msg| %>
        <li class="error-message"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= form.text_field :text %>
  </p>

  <%= form.submit %>

<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<%= link_to 'view', question_path(@question) %>

<%= render 'form' %>
<% @question.answers.each do |answer| %>
  <p>
    <%= answer.text %> |
    <%= link_to 'delete', [answer.question, answer],
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

<%= render 'answers/form' %>

app/views/questions/index.html.erb
<h1>Question List</h1>

<ul class="question-list">
  <% @questions.each do |question| %>
    <li class="question-list__item">
    <%= question.text %> |
    <%= link_to 'view', question_path(question) %> |
    <%= link_to 'edit', edit_question_path(question) %> |
    <%= link_to 'delete', question_path(question),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<%= link_to 'new question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>
<%= render 'form' %>

app/views/questions/show.html.erb
<h1>View Question</h1>
<%= link_to 'edit', edit_question_path(@question) %>
<p>
  <%= @question.text %>
</p>
<p>
  <%= render @question.answers %>
</p>

app/views/welcome/index.html.erb
<h1>Hello!</h1>